Select BUY.PUR_PO_MST_MID, BUY.PUR_SUP_MID,SUP.SHORT_NM ,TO_CHAR(BUY.BILL_INVOICE_DT, 'Month DD, YYYY'),(BUY.BILL_TOTAL_LOCAL-BUY.DISCOUNT_TOTAL) "PURCHASE",
NVL(RET.TTL_PUR_RET_AMT, 0) "PURCHASE RET",BUY.DISCOUNT_TOTAL, (BUY.BILL_TOTAL_LOCAL-BUY.DISCOUNT_TOTAL)-NVL(RET.TTL_PUR_RET_AMT,0) "TOTAL",
RET.NARRATION ,MST.IS_APPLIED
from PUR_SUBMITED_BILL_MST BUY
LEFT JOIN PUR_PUR_RET RET ON BUY.PUR_PO_MST_MID=RET.PUR_PO_MST_MID
INNER JOIN PUR_SUP SUP ON BUY.PUR_SUP_MID=SUP.MID
INNER JOIN PUR_PO_MST MST ON MST.MID=BUY.PUR_PO_MST_MID
ORDER BY BUY.PUR_SUP_MID, BUY.BILL_INVOICE_DT;
